[package]
name = "midi-shenanigans"
version = "0.0.1"
authors = ["Yui <yui.github@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.7.0"
wmidi = "4.0.4"
